# Generated by Django 5.0.6 on 2024-06-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Site Title')),
                ('site_name', models.CharField(max_length=255, verbose_name='Site Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/favicons/', verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logos/', verbose_name='Logo')),
                ('banner_img', models.ImageField(upload_to='images/', verbose_name='Banner Image')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Footer Text')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('sliders', models.ManyToManyField(blank=True, to='core.slider', verbose_name='Slider Content')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
