# Generated by Django 5.0.6 on 2024-06-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_specification_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Specifications'),
        ),
    ]
