# Generated by Django 5.0.6 on 2024-06-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='banner_img',
            field=models.ImageField(upload_to='images/banner', verbose_name='Banner Image'),
        ),
    ]
