# Generated by Django 5.0.6 on 2024-06-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
