# Generated by Django 5.0.6 on 2024-06-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
